# Generated by Django 4.0.5 on 2022-06-30 06:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='teacherprofile',
            name='is_classteacher',
        ),
        migrations.AddField(
            model_name='user',
            name='is_classteacher',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='is_hod',
            field=models.BooleanField(default=False),
        ),
    ]
