# Generated by Django 4.0.5 on 2022-06-09 14:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0001_initial'),
        ('users', '0002_teacherprofile_created_at_teacherprofile_updated_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacherprofile',
            name='course',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='course.course'),
        ),
    ]
