# Generated by Django 4.0.5 on 2022-07-01 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0001_initial'),
        ('users', '0002_remove_teacherprofile_is_classteacher_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacherprofile',
            name='course',
            field=models.ManyToManyField(blank=True, to='course.course'),
        ),
    ]
