# Generated by Django 4.0.5 on 2022-06-06 08:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_remove_teacherprofile_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacherprofile',
            name='teacherID',
            field=models.IntegerField(null=True, unique=True),
        ),
    ]
