# Generated by Django 4.0.5 on 2022-07-03 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_teacherprofile_course'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='teacherprofile',
            name='department',
        ),
        migrations.AddField(
            model_name='user',
            name='department',
            field=models.CharField(blank=True, choices=[('Computer Engineering', 'Computer Engineering'), ('Electronics and Telecommunication Engineering', 'Electronics and Telecommunication Engineering'), ('Information Technology', 'Information Technology'), ('Mechanical Engineering', 'Mechanical Engineering')], default=1, max_length=50, null=True),
        ),
    ]
