# Generated by Django 4.0.5 on 2022-06-09 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0001_initial'),
        ('users', '0003_alter_teacherprofile_course'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='teacherprofile',
            name='course',
        ),
        migrations.AddField(
            model_name='teacherprofile',
            name='course',
            field=models.ManyToManyField(to='course.course'),
        ),
    ]
