# Generated by Django 4.0.3 on 2022-06-06 07:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('sem', models.IntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5'), (6, '6'), (7, '7'), (8, '8')])),
                ('dept', models.CharField(choices=[('Comps', 'Computer Engineering'), ('IT', 'Information Technology'), ('EXTC', 'Electronics and Telecommunication Engineering'), ('Mech', 'Mechanical Engineering')], max_length=50)),
            ],
        ),
    ]
