# Generated by Django 4.0.3 on 2022-06-06 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0003_alter_course_dept'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='dept_level',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='course',
            name='institue_level',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='course',
            name='is_elective',
            field=models.BooleanField(default=False),
        ),
    ]
