# Generated by Django 4.0.3 on 2022-06-06 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0004_course_dept_level_course_institue_level_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='code',
            field=models.CharField(default=0, max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='course',
            name='scheme',
            field=models.CharField(default=0, max_length=10),
            preserve_default=False,
        ),
    ]
