# Generated by Django 4.0.5 on 2022-06-07 08:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0006_alter_course_dept'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='sem',
            field=models.IntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5'), (6, '6'), (7, '7'), (8, '8')], verbose_name='Semester'),
        ),
    ]
