# Generated by Django 4.0.5 on 2022-08-19 13:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cls', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='class',
            unique_together={('id', 'class_name', 'department')},
        ),
    ]
