# Generated by Django 4.0.5 on 2022-06-30 17:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_remove_teacherprofile_is_classteacher_and_more'),
        ('cls', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='class',
            name='class_teacher',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.teacherprofile'),
        ),
        migrations.AlterField(
            model_name='class',
            name='department',
            field=models.CharField(blank=True, choices=[('Computer Engineering', 'Computer Engineering'), ('Electronics and Telecommunication Engineering', 'Electronics and Telecommunication Engineering'), ('Information Technology', 'Information Technology'), ('Mechanical Engineering', 'Mechanical Engineering')], max_length=100, null=True),
        ),
    ]
