# Generated by Django 4.0.5 on 2022-08-31 09:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cls', '0003_alter_class_unique_together'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='class',
            unique_together=set(),
        ),
    ]
