# Generated by Django 4.0.5 on 2022-07-23 07:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('cls', '__first__'),
        ('course', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='student',
            fields=[
                ('roll_no', models.IntegerField(blank=True, null=True)),
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('cls', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='cls.class')),
                ('course', models.ManyToManyField(blank=True, to='course.course')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
