# Generated by Django 4.0.5 on 2022-06-25 13:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cls', '0002_remove_class_students'),
        ('student', '0002_remove_student_dob_remove_student_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='cls',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='cls.class'),
        ),
    ]
