# Generated by Django 4.0.5 on 2022-06-25 13:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cls', '0002_remove_class_students'),
        ('student', '0003_student_cls'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='cls',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='cls.class'),
        ),
    ]
