# Generated by Django 4.0.5 on 2022-07-23 07:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendance',
            name='date',
            field=models.DateField(default='2018-10-23'),
        ),
        migrations.AddField(
            model_name='attendanceclass',
            name='date',
            field=models.DateField(default='2018-10-23'),
        ),
    ]
