# Generated by Django 4.0.5 on 2022-09-02 05:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='attendanceclass',
            name='assigntime',
        ),
        migrations.AddField(
            model_name='attendanceclass',
            name='date',
            field=models.DateField(default='2022-10-23'),
        ),
        migrations.AddField(
            model_name='attendanceclass',
            name='day',
            field=models.CharField(choices=[('Monday', 'Monday'), ('Tuesday', 'Tuesday'), ('Wednesday', 'Wednesday'), ('Thursday', 'Thursday'), ('Friday', 'Friday')], default=1, max_length=15),
        ),
        migrations.AddField(
            model_name='attendanceclass',
            name='period',
            field=models.CharField(choices=[('9:30 - 10:30', '9:30 - 10:30'), ('10:30 - 11:30', '10:30 - 11:30'), ('11:30 - 12:30', '11:30 - 12:30'), ('12:30 - 1:30', '12:30 - 1:30'), ('2:30 - 3:30', '2:30 - 3:30'), ('3:30 - 4:30', '3:30 - 4:30'), ('4:30 - 5:30', '4:30 - 5:30')], default='11:00 - 11:50', max_length=50),
        ),
    ]
