# Generated by Django 4.0.5 on 2022-09-02 05:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0002_remove_attendanceclass_assigntime_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='assigntime',
            unique_together={('assign', 'period', 'day')},
        ),
    ]
